### ISSUE TITLE
Changing List to ArrayList

### ISSUE THREAD

**Issue by sarahmehmedi** [dallen4/TwitterMessenger#1]
I liked how the code had comments so that I could understand what you were doing. I suggest to maybe change your Lists to new ArrayLists
ex:
 In Tweet.java line 20: `private List<String> URLEntities;` 
After: ` private final static List<String> URLEntities = new ArrayList<String>();` 

This might help with passing the tests, however with adding ArrayLists, there are certain syntax items that would need to be changed within the functions. Another small thing would be to separate parts into classes (hashtags, mentions, etc).

**Comment by dallen4** [comment]
Thanks for the feedback. I will look into ArrayLists (another peer mentioned/suggested that as well).
