### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by larpfairy** [dallen4/TwitterMessenger#3]
So far you code looks very good. It is well documented and organized nicely. I liked that you separated a lot of the actual handling of the tweet into its own class. It makes the code very easy to understand. Your tests that you have set up are well thought out, and I know you probably have yet to add more. The best thing imo about this is the use of regular expressions to determine the mentions, hashtags, and urls. The regex combined with the pingurl method is very good at avoiding broken links. I have looked and tried to figure out what may be causing the test failures but have not had any luck finding the source. I know that I personally had a lot of problems when I was using Lists. In the end I switched to ArrayLists and my problems went away.

**Comment by dallen4** [comment]
Thanks for the feedback. I will look into ArrayLists (another peer already mentioned/suggested that as well).
